[2022-05-28 19:29:44,390] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: social_sentiment_dag.fetch_social_sentiment_from_GOOGL manual__2022-05-28T17:28:48+00:00 [queued]>
[2022-05-28 19:29:44,394] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: social_sentiment_dag.fetch_social_sentiment_from_GOOGL manual__2022-05-28T17:28:48+00:00 [queued]>
[2022-05-28 19:29:44,394] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 19:29:44,394] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-28 19:29:44,394] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 19:29:44,406] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_social_sentiment_from_GOOGL> on 2022-05-28 17:28:48+00:00
[2022-05-28 19:29:44,407] {standard_task_runner.py:52} INFO - Started process 29619 to run task
[2022-05-28 19:29:44,409] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'social_sentiment_dag', 'fetch_social_sentiment_from_GOOGL', 'manual__2022-05-28T17:28:48+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/load_social_sentiment_dag.py', '--cfg-path', '/tmp/tmpw41yrvch', '--error-file', '/tmp/tmp2kfs1q6s']
[2022-05-28 19:29:44,410] {standard_task_runner.py:80} INFO - Job 236: Subtask fetch_social_sentiment_from_GOOGL
[2022-05-28 19:29:44,438] {logging_mixin.py:109} INFO - Running <TaskInstance: social_sentiment_dag.fetch_social_sentiment_from_GOOGL manual__2022-05-28T17:28:48+00:00 [running]> on host DESKTOP-O4M0F04.localdomain
[2022-05-28 19:29:44,474] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=social_sentiment_dag
AIRFLOW_CTX_TASK_ID=fetch_social_sentiment_from_GOOGL
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T17:28:48+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-28T17:28:48+00:00
[2022-05-28 19:29:44,485] {logging_mixin.py:109} INFO - Successful connection to mongo db
[2022-05-28 19:29:50,149] {python.py:175} INFO - Done. Returned value was: None
[2022-05-28 19:29:50,155] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=social_sentiment_dag, task_id=fetch_social_sentiment_from_GOOGL, execution_date=20220528T172848, start_date=20220528T172944, end_date=20220528T172950
[2022-05-28 19:29:50,209] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-28 19:29:50,216] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
